### ISSUE TITLE
Referencing

### ISSUE THREAD

**Issue by tooga** [MartinBrugnara/Economics_EIT_1516#1]
As I said in the battle template it was said that the referencing should be Harvard style, which is in text marked as (Author, Year) and in reference list:
- Article: Last name, initial of the name; Last name, initial of the name. “title of article” in Eventually Manual or Book (year) or journal, Editor, Volume, page. 
  - Example Bonifacio, M. “The tech bat” in New Teaching Methods (2013). Universal Journal of European Education, Cambridge University Press, VOL II, pg. 65-66.
- Book: Last name, initial of the name; Last name, initial of the name. Title of Book Editor (Date), page.
  - Example Bonifacio, M. New Teaching Methods (2013), Cambridge University Press, pg. 65-66.
- Reference to multimedia: weblink or other address (e.g. repository, author, name, source, year)

I could have done that referencing. But seems like for Latex you should download some Natbib extensions for Harvard and I have no idea how to start modifying that Latex now so I don't really know. I can write the reference list in plain text if you want to convert it to Latex form. Or then just go with what we have now.

**Comment by MartinBrugnara** [comment]
I read it.
But all our reference are to webpages or online documents.

So no clear author exists(mostly), year is really provided..
when it is I inserted it.

a plain text file with the information I did not wrote for each ref. would be fine.. I will update it later this afternoon..

P.s. anyhow I thing that as they currently are would be enough..

**Comment by tooga** [comment]
I did the reference list in the style that was asked and added the reference styles that should be in text. If you want you can add the stuff, but don’t matter that much for me anymore. 

There are just 3 duplicate references now, that’s not so good thing. On the other hand without them we drop under the required 20 refs.
